### ISSUE TITLE
feat: view-only mode

### ISSUE THREAD

**Issue by stephancill** [stephancill/opencast#3]
You should be able to browse content without having a signer for the app

Will require view-only states for the components that trigger write actions and might require disabling features that depend on the signed-in user's FID

**Comment by MicahZoltu** [comment]
I'm essentially waiting for this before using OpenCast (or really any part of Farcaster).  All of the various Farcaster tools seem to require either a mobile app install (Warpcast) or a centralized account (Farcord).  This tool looks like it supports just SIWE login, but I'm quite hesitant to give out my account or go through the effort of creating a new temporary one just so I can see what the app looks like and/or read a couple things first.
