### ISSUE TITLE
opencast.stephancill.co.za TLS certificate broken and page not working.

### ISSUE THREAD

**Issue by MicahZoltu** [stephancill/opencast#39]
![image](https://github.com/user-attachments/assets/527562f6-d1f6-4340-8904-d16244a96424)

I noticed that you have been actively iterating on OpenCast lately so I figured I would give it another try to see if some of the bugs I encountered previously were fixed.  Unfortunately, the Web UI appears to be broken as the TLS certificate is bad and if I force allow it it just shows the above error.

**Comment by stephancill** [comment]
Hi @MicahZoltu, was actually going to reach out to you. I don’t have a public hosted instance yet but it has been rearchitected to be self-hostable again

**Comment by MicahZoltu** [comment]
Is there, or are there plans for, a docker-compose.yml file (or similar) that can be used to spin up everything needed without having to build from source or manually configure/connect things?

**Comment by stephancill** [comment]
@MicahZoltu added a docker-compose and instructions in readme
