### ISSUE TITLE
chore: add a docker-compose.yml to make running opencast easier

### ISSUE THREAD

**Issue by stephancill** [stephancill/opencast#40]
Add a docker-compose.yml that runs the indexer and opencast

You should be able to run opencast by providing env values and running `docker-compose up`

Might require publishing an image of the lazy indexer to the docker registry

**Comment by dalechyn** [comment]
Putting 100 USDC reward on this one!

Add your wallet address with the PR and on merge, message me at https://warpcast.com/dalechyn.eth.

**Comment by gabrieltemtsen** [comment]
https://github.com/stephancill/opencast/pull/41

**Comment by stephancill** [comment]
fixed by #41
